### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split') - Codecept with Xray

### ISSUE THREAD

**Issue by MariaAvramescu26** [medtoure18/codeceptjs-xray-helper#14]
Trying to connect codeceptjs with Xray by using your plugin. 
There is an error. Can you please help me out? Thank you 

Error processing global.after event:
TypeError: Cannot read properties of undefined (reading 'split')
    at flp-end-to-end-front\node_modules\codeceptjs-xray-helper\index.js:114:77
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (flp-end-to-end-front\node_modules\codeceptjs-xray-helper\index.js:109:26)
    at EventEmitter.emit (node:events:514:28)
    at Object.emit (flp-end-to-end-front\node_modules\codeceptjs\lib\event.js:145:28)
    at done (Cflp-end-to-end-front\node_modules\codeceptjs\lib\codecept.js:188:15)

**Comment by medtoure18** [comment]
Hi Maria,
It's been 3 years since i worked last time on codeceptjs.
Maybe the new version of codeceptjs is not Compatible with the helper anymore.
Are you on jira server or jira cloud?
This helper is only Compatible with jira server.
Otherwise you can check the file 
node_modules\codeceptjs-xray-helper\index.js on line 114.
Its seems an object is undifined there

**Comment by MariaAvramescu26** [comment]
Dear medtoure,

Thank you for your prompt response. 

Adding the `node_modules` directory to the remote repository is generally discouraged due to its large size and the potential for version conflicts. Instead, it's recommended to exclude it from version control and have developers install dependencies locally using the `npm install` or `yarn install` commands.

I understand that it has been some time since you last worked on CodeceptJS, and I respect your expertise. Considering the error I encountered, would it be possible for you to update the plugin to ensure compatibility with the latest version of CodeceptJS? This would greatly help in maintaining a clean and efficient development environment for all users.

Thank you again for your assistance. I look forward to your guidance on resolving this matter.

Best regards,
Maria

**Comment by medtoure18** [comment]
Sorry but i dont have time to work on it anymore. But if you fix it on your side i will accept your PR. 
And release a new version.
So you will not have to add your not module to your project.
Other wise you can also clone the project on a github project of your own and publish it as a new npm library

**Comment by MariaAvramescu26** [comment]
Hello,
I'm currently facing issues pushing changes to your repository in another branch. It seems I'm encountering a permission error (403). Do you have an alternative communication method we can use to ease up the process?

Thank you, Med!

**Comment by medtoure18** [comment]
Hi Maria,
I gave the rights on the project.
Now you can create your own branch.
Have a great day,

**Comment by MariaAvramescu26** [comment]
I still do not manage..
```
remote: Permission to medtoure18/codeceptjs-xray-helper.git denied to MariaAvramescu26.
fatal: unable to access 'https://github.com/medtoure18/codeceptjs-xray-helper.git/': The requested URL returned error: 403
```

**Comment by medtoure18** [comment]
You did not accept my github invitation.
This is my email to ease the process : mohamed.toure.obs@gmail.com

**Comment by MariaAvramescu26** [comment]
Now the split of undefined is showing up on a different line, but not when I point to the index.js, just when I use the beta version. Very strange, I will anyways have a look , thank you
